/**
 * unknown-keys.ts — auto-generated by deploy-content-to-github
 *
 * Keys that exist in the content database but could not be deployed directly
 * into source files (e.g. keys used in dynamic contexts, meta tags, or
 * server-side rendered paths that the source scanner cannot reach).
 *
 * The content system checks this file as a fallback AFTER the database and
 * BEFORE the hardcoded fallback prop, so values here are always live without
 * a redeploy.
 *
 * DO NOT edit this file manually — it is overwritten on every deploy.
 * Last updated: (never — initial empty file)
 */

/**
 * Map of content key → value.
 * Keyed by the original content key string (not the JS identifier).
 * This is what DataContext reads at runtime.
 */
export const unknownKeysMap: Record<string, string> = {
  // entries are written here by the deploy function
};
